name: MSPOC Workflow

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  OUTPUT_PATH: ${{ github.workspace}}/.output

jobs:
#################################################################################################
###   CI - MSPOC.CATALOG.SERVICE   ##############################################################
#################################################################################################
  CATALOG-SERVICE-CI:
    name: "Catalog Service CI"
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: MSPOC.Catalog.Service
      SOLUTION_PATH: ./MSPOC.Catalog.Service

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION_PATH }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
        
    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --output ${{ env.OUTPUT_PATH }}
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
       name: ${{ env.PROJECT_NAME }}.zip
       path: ${{ env.OUTPUT_PATH }}

#################################################################################################
###   CI - MSPOC.CUSTOMER.SERVICE   #############################################################
#################################################################################################
  CUSTOMER-SERVICE-CI: 
    name: "Customer Service CI"
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: MSPOC.Customer.Service
      SOLUTION_PATH: ./MSPOC.Customer.Service

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION_PATH }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
        
    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --output ${{ env.OUTPUT_PATH }}
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
       name: ${{ env.PROJECT_NAME }}.zip
       path: ${{ env.OUTPUT_PATH }}

#################################################################################################
###   CI - MSPOC.ORDER.SERVICE   ################################################################
#################################################################################################
  ORDER-SERVICE-CI:
    name: "Order Service CI"
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: MSPOC.Order.Service
      SOLUTION_PATH: ./MSPOC.Order.Service

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION_PATH }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
        
    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --output ${{ env.OUTPUT_PATH }}
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
       name: ${{ env.PROJECT_NAME }}.zip
       path: ${{ env.OUTPUT_PATH }}

#################################################################################################
###   CD - MSPOC.CATALOG.SERVICE   ##############################################################
#################################################################################################
  CATALOG-SERVICE-DOCKER:
    name: "Catalog Service DockerHub"
    needs: [CATALOG-SERVICE-CI]
    runs-on: ubuntu-latest
    
    env:
      CONTEXT_PATH: ./MSPOC.Catalog.Service
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_LOGIN }}/mspoc.catalog.service

    steps: 
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}
#          tags: |
#            ${{ env.DOCKER_IMAGE }}:latest
#            ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
  
#################################################################################################
###   CD - MSPOC.CUSTOMER.SERVICE   #############################################################
#################################################################################################
  CUSTOMER-SERVICE-DOCKER:
    name: "Customer Service DockerHub"
    needs: [CUSTOMER-SERVICE-CI]
    runs-on: ubuntu-latest
    
    env:
      CONTEXT_PATH: ./MSPOC.Customer.Service
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_LOGIN }}/mspoc.customer.service

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}
#          tags: |
#            ${{ env.DOCKER_IMAGE }}:latest
#            ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

#################################################################################################
###   CD - MSPOC.ORDER.SERVICE   ################################################################
#################################################################################################
  ORDER-SERVICE-DOCKER:
    name: "Order Service DockerHub"
    needs: [ORDER-SERVICE-CI]
    runs-on: ubuntu-latest
    
    env:
      CONTEXT_PATH: ./MSPOC.Order.Service
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_LOGIN }}/mspoc.order.service

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}
#          tags: |
#            ${{ env.DOCKER_IMAGE }}:latest
#            ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
