name: MSPOC-Workflow

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  MSPOC_CATALOG_SERVICE: MSPOC.Catalog.Service
  MSPOC_CUSTOMER_SERVICE: MSPOC.Customer.Service
  MSPOC_ORDER_SERVICE: MSPOC.Order.Service

jobs:
#################################################################################################
###   MSPOC.CATALOG.SERVICE   ###################################################################
#################################################################################################
  CATALOG-SERVICE-CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Build
      run: dotnet build --no-restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./$MSPOC_CATALOG_SERVICE

  CATALOG-SERVICE-CD:
    needs: [CATALOG-SERVICE-CI]
    runs-on: ubuntu-latest

    steps:
      - name: Push DockerHub
        run: echo Hello, world!
  
#################################################################################################
###   MSPOC.CUSTOMER.SERVICE   ##################################################################
#################################################################################################

  CUSTOMER-SERVICE-CI: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./$MSPOC_CUSTOMER_SERVICE
      
    - name: Build
      run: dotnet build --no-restore ./$MSPOC_CUSTOMER_SERVICE
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./$MSPOC_CUSTOMER_SERVICE

  CUSTOMER-SERVICE-CD:
    needs: [CUSTOMER-SERVICE-CI]
    runs-on: ubuntu-latest

    steps:
      - name: Push DockerHub
        run: echo Hello, world!

#################################################################################################
###   MSPOC.ORDER.SERVICE   #####################################################################
#################################################################################################
 
  ORDER-SERVICE-CI: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Build
      run: dotnet build --no-restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./$MSPOC_CATALOG_SERVICE

  ORDER-SERVICE-CD:
    needs: [ORDER-SERVICE-CI]
    runs-on: ubuntu-latest

    steps:
      - name: Push DockerHub
        run: echo Hello, world!
