name: MSPOC Workflow

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  MSPOC_CATALOG_SERVICE: MSPOC.Catalog.Service
  MSPOC_CUSTOMER_SERVICE: MSPOC.Customer.Service
  MSPOC_ORDER_SERVICE: MSPOC.Order.Service
  OUTPUT_PATH: ${{ github.workspace}}/.output

jobs:
#################################################################################################
###   MSPOC.CATALOG.SERVICE   ###################################################################
#################################################################################################
  CI_CATALOG-SERVICE:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Build
      run: dotnet build --no-restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./$MSPOC_CATALOG_SERVICE
        
    - name: Publish
      run: dotnet publish ./$MSPOC_CATALOG_SERVICE --configuration Release --output $OUTPUT_PATH
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
       name: $MSPOC_CATALOG_SERVICE
       path: $OUTPUT_PATH

  CD_CATALOG-SERVICE:
    needs: [CI_CATALOG-SERVICE]
    runs-on: ubuntu-latest

    steps:
      - name: Push DockerHub
        run: echo Hello, world!
  
#################################################################################################
###   MSPOC.CUSTOMER.SERVICE   ##################################################################
#################################################################################################

  CI_CUSTOMER-SERVICE: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./$MSPOC_CUSTOMER_SERVICE
      
    - name: Build
      run: dotnet build --no-restore ./$MSPOC_CUSTOMER_SERVICE
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./$MSPOC_CUSTOMER_SERVICE

  CD_CUSTOMER-SERVICE:
    needs: [CI_CUSTOMER-SERVICE]
    runs-on: ubuntu-latest

    steps:
      - name: Push DockerHub
        run: echo Hello, world!

#################################################################################################
###   MSPOC.ORDER.SERVICE   #####################################################################
#################################################################################################
 
  CI_ORDER-SERVICE: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Build
      run: dotnet build --no-restore ./$MSPOC_CATALOG_SERVICE
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./$MSPOC_CATALOG_SERVICE

  CD_ORDER-SERVICE:
    needs: [CI_ORDER-SERVICE]
    runs-on: ubuntu-latest

    steps:
      - name: Push DockerHub
        run: echo Hello, world!
